### ISSUE TITLE
Full window Higlighted and cron icon

### ISSUE THREAD

**Issue by fuzebox1** [rovellipaolo/gnome-shell-extension-sermon#13]
When i click the icon and mouse over the window the whole window lights up with system theme highlight color. I would assume only the items should light up. Cant really see what im selecting with my color scheme.

Also i disabled cron in settings, and i would like the cron icon to dissapear when not enabled.

Thank you for a otherwise great ext.

**Comment by rovellipaolo** [comment]
> Cant really see what im selecting with my color scheme.

That shouldn’t happen, might be an issue related to your specific colour scheme.
Which version of GNOME are you using? Which custom theme?!

I am sorry for the inconvenience but, please, note that I test the extension only with vanilla GNOME and Ubuntu/Yaru. That said, if you want to do a pull request fixing it for your color scheme, I will gladly review and merge it.


> Also i disabled cron in settings, and i would like the cron icon to dissapear when not enabled.

It should indeed disappear. However, due to a technical limitation, it happens only at the next reload. Have you tried to log out and then log in again, or reboot the computer?

**Comment by fuzebox1** [comment]
I use endevouros's latest gnome, should be bone stock. I use a theme called Klaus, a gruvbox theme. Pretty old so probably time to change to another gruvbox theme. Using a few other themes, the whole window highlights but with those the individual actions had a different color. It appears to not be a specific theme issue.
A relog fixed the icon, but not the highlight issue.

**Comment by rovellipaolo** [comment]
Ok, I guess the highlight issue is the same of: https://github.com/rovellipaolo/gnome-shell-extension-sermon/issues/9
Closing this one. I will try to address the latter when I have time, sorry for the inconvenience.

**Comment by rovellipaolo** [comment]
Fixed: https://github.com/rovellipaolo/gnome-shell-extension-sermon/commit/953e8159b90166adedf00c5d0595f4c02975515d
The fix has been released with version 22 of the extension (should be available in a couple of days).
